name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Remove Build Folders
        run: rm -rf dist output out

      - name: Install Dependencies
        run: yarn install -y

      - name: Package Application
        run: yarn package

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn build:linux --x64

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: yarn build:win --x64

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
